#!/bin/sh
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin
export HOME=/root

set -ex

resizefs(){
	fstype=$1
	part=$2
	case $fstype in
	ext4)
		e2fsck -fp $part
		e2fsck -fy $part
		e2fsck -f $part || true
		resize2fs -f $part || true
		e2fsck -fy $part
		resize2fs -f $part || true
		e2fsck -fp $part
		e2fsck -fy $part
	  ;;
	btrfs)
		mkdir -p /mnt
		mount $part /mnt
		btrfs filesystem resize max /mnt
		umount /mnt
	esac
}

start(){
	set -x
	MMC=mmcblk2
	MMCDEV=/dev/${MMC}
	sleep 5
	PARTS=$(eptdump $MMCDEV)
	echo "$PARTS"

	ENV_OFF=$(echo "$PARTS" | grep 'env' | cut  -f3)
	ENV_SIZE=$(echo "$PARTS" | grep 'env' | cut  -f2)
	BOOT_OFF=$(echo "$PARTS" | grep 'armbian_boot' | cut  -f3)
	BOOT_SIZE=$(echo "$PARTS" | grep 'armbian_boot' | cut  -f2)
	ROOT_OFF=$(echo "$PARTS" | grep 'armbian_rootfs' | cut  -f3)
	ROOT_SIZE=$(echo "$PARTS" | grep 'armbian_rootfs' | cut  -f2)

	TOTAL_SIZE=$(( $(cat /sys/class/block/${MMC}/size) * 512 ))

	echo "$MMCDEV $ENV_OFF 0x10000 0x200" > /etc/fw_env.config

	fw_setenv -s /aml_env

	truncate -s $TOTAL_SIZE disk.tmp

	parted -s "disk.tmp" mklabel msdos
	parted -s "disk.tmp" mkpart primary fat32 ${BOOT_OFF}B $(( BOOT_OFF + BOOT_SIZE - 1))B
	parted -s "disk.tmp" mkpart primary ext4 ${ROOT_OFF}B $((ROOT_OFF + ROOT_SIZE - 1))B
	dd if=disk.tmp of=${MMCDEV} bs=1 seek=444 skip=444 count=68 conv=fsync oflag=direct
	rm -f "disk.tmp"
	partprobe $MMCDEV

	fstype=$(blkid ${MMCDEV}p2 | grep -o 'TYPE=".*"' | awk -F'"' '{print $2}')
	resizefs $fstype ${MMCDEV}p2

	echo "set part done" > /var/log/setpart
}
start 2>&1|tee -a /dev/tty1 | tee -a /dev/ttyAML0
reboot

